#!/usr/bin/env python3

import socket, struct, argparse

HOST = "127.0.0.1"
PORT = 58351

def main(nomefile):
    with open(nomefile, "r") as f:
        for line in f:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.connect((HOST, PORT))
                connection_type = 0
                # Comunica che è una connessione di tipo A
                s.sendall(struct.pack("<i",connection_type)) 
                encoded_line = str.encode(line)
                length_bytes = len(encoded_line)
                s.sendall(struct.pack("<i",length_bytes))
                s.sendall(encoded_line)
                s.shutdown(socket.SHUT_RDWR)



parser = argparse.ArgumentParser()
parser.add_argument("nomefile", help="nome del file da leggere")
args = parser.parse_args()
main(args.nomefile)

